name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# https://github.com/ruby/setup-ruby  
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: ['3.0', '3.2']
    
    runs-on: ${{ matrix.os }}

    if: (!contains(github.event.head_commit.message, '[skip ci]')) && (!contains(github.event.head_commit.message, '[ci skip]'))

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test
